/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.FormChatLieu;

/**
 *
 * @author NhatMinh
 */
public class QLBH extends javax.swing.JFrame {

    /**
     * Creates new form QLBH
     */
    public QLBH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        Taptin = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();
        Danhmuc = new javax.swing.JMenu();
        ChatLieu = new javax.swing.JMenuItem();
        NhanVien = new javax.swing.JMenuItem();
        KhachHang = new javax.swing.JMenuItem();
        HangHoa = new javax.swing.JMenuItem();
        HoaDon = new javax.swing.JMenu();
        HoaDonBan = new javax.swing.JMenuItem();
        TimKiem = new javax.swing.JMenu();
        TimHoaDon = new javax.swing.JMenuItem();
        TimHang = new javax.swing.JMenuItem();
        TimKhachHang = new javax.swing.JMenuItem();
        BaoCao = new javax.swing.JMenu();
        HangTon = new javax.swing.JMenuItem();
        DoanhThu = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        HienHelp = new javax.swing.JMenu();
        VaiNet = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Taptin.setText("Tập Tin");

        Exit.setText("Thoát");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        Taptin.add(Exit);

        jMenuBar1.add(Taptin);

        Danhmuc.setText("Danh Mục");

        ChatLieu.setText("Chất Liệu");
        ChatLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChatLieuActionPerformed(evt);
            }
        });
        Danhmuc.add(ChatLieu);

        NhanVien.setText("Nhân Viên");
        NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhanVienActionPerformed(evt);
            }
        });
        Danhmuc.add(NhanVien);

        KhachHang.setText("Khách Hàng");
        Danhmuc.add(KhachHang);

        HangHoa.setText("Hàng Hoá");
        HangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HangHoaActionPerformed(evt);
            }
        });
        Danhmuc.add(HangHoa);

        jMenuBar1.add(Danhmuc);

        HoaDon.setText("Hoá Đơn");

        HoaDonBan.setText("Hoá Đơn Bán");
        HoaDon.add(HoaDonBan);

        jMenuBar1.add(HoaDon);

        TimKiem.setText("Tìm Kiếm");

        TimHoaDon.setText("Tìm Hoá Đơn");
        TimKiem.add(TimHoaDon);

        TimHang.setText("Tìm Hàng");
        TimKiem.add(TimHang);

        TimKhachHang.setText("Tìm Khách Hàng");
        TimKiem.add(TimKhachHang);

        jMenuBar1.add(TimKiem);

        BaoCao.setText("Báo Cáo");

        HangTon.setText("Hàng Tồn");
        BaoCao.add(HangTon);

        DoanhThu.setText("Doanh Thu");
        BaoCao.add(DoanhThu);

        jMenuBar1.add(BaoCao);

        Help.setText("Trợ Giúp");

        HienHelp.setText("Hiện Trợ Giúp");
        Help.add(HienHelp);

        VaiNet.setText("Vài Nét");
        Help.add(VaiNet);

        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhanVienActionPerformed
        // TODO add your handling code here:
        new GUINhanVien().setVisible(true);
    }//GEN-LAST:event_NhanVienActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void ChatLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChatLieuActionPerformed
        // TODO add your handling code here:
        new GUIChatLieu().setVisible(true);
    }//GEN-LAST:event_ChatLieuActionPerformed

    private void HangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HangHoaActionPerformed
        // TODO add your handling code here:       
        new GUIHangHoa().setVisible(true);
    }//GEN-LAST:event_HangHoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLBH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLBH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BaoCao;
    private javax.swing.JMenuItem ChatLieu;
    private javax.swing.JMenu Danhmuc;
    private javax.swing.JMenuItem DoanhThu;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem HangHoa;
    private javax.swing.JMenuItem HangTon;
    private javax.swing.JMenu Help;
    private javax.swing.JMenu HienHelp;
    private javax.swing.JMenu HoaDon;
    private javax.swing.JMenuItem HoaDonBan;
    private javax.swing.JMenuItem KhachHang;
    private javax.swing.JMenuItem NhanVien;
    private javax.swing.JMenu Taptin;
    private javax.swing.JMenuItem TimHang;
    private javax.swing.JMenuItem TimHoaDon;
    private javax.swing.JMenuItem TimKhachHang;
    private javax.swing.JMenu TimKiem;
    private javax.swing.JMenuItem VaiNet;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
